### Step 3 Postprocessing: SVD with KNN

After matrix factorization, postporcessing will be performed to improve accuracy.

KNN Function
```{r}
vec <- function(x) {
  
  return(sqrt(sum(x^2)))
  
  }
pred_knn <- function(data_train, data_test, q)
{
  
  norm_q <- apply(q,2,vec)
  sim <- t(t((t(q) %*% q)/ norm_q) / norm_q)
  colnames(sim) <- colnames(q)
  rownames(sim) <- colnames(q)
  pred_test <- rep(0,nrow(data_test))
  
  for (i in 1:nrow(data_test)){
    user_id <- data_test$userId[i]
    movie_id <- data_test$movieId[i]
    train <- data_train[data_train$userId == user_id & data_train$movieId != movie_id,]
    movie_train <- train$movieId
    sim_vec <- sim[rownames(sim) == movie_id, colnames(sim) %in% movie_train]
    movie <- names(sim_vec)[which.max(sim_vec)]
    pred_test[i] <- train[train$movieId == movie,][3]
  }
  
  pred_test <- as.matrix(unlist(pred_test))
  rmse_test <- sqrt(mean((data_test$rating-pred_test)^2))
  return(list(pred_test = pred_test, rmse_test = rmse_test))
  
}
```

#### Step 3.1. RMSE of Algorithm with Postprocessing (SVD with KNN)

result_sgd5000 is their algorithm in this case
```{r}
 result_sgd5000 <- gradesc(f = 10, lambda = 0.1,lrate = 0.01, max.iter = 100, stopping.deriv = 0.01,
                    data = data, train = data_train, test = data_test)
 
 save(result_sgd5000, file = "~/Desktop/Spring 2020/ADS/Project4/output/mat_fac_sgd5000.RData")
```

```{r}
load(file = "~/Desktop/Spring 2020/ADS/Project4/output/mat_fac_sgd5000.Rdata")
q <- result_sgd5000$q
p2_result_test <- pred_knn(data_train, data_test, q)
test_rmse_p2 <- p2_result_test['rmse_test']
cat("The RMSE of Algorithm with Postprocessing (SVD with KNN) is", as.numeric(test_rmse_p2))
```